pipeline {
    agent any

    stages {
        stage('Build & Test') {
            steps {
                dir('calculator-app') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('Package JAR') {
            steps {
                dir('calculator-app') {
                    sh 'mvn package'
                }
            }
        }

        stage('Install to Local Repo') {
            steps {
                dir('calculator-app') {
                    sh 'mvn install'
                }
            }
        }
    }

    post {
        failure {
            echo 'Build failed'
        }
        success {
            echo 'Build successful'
        }
    }
}
